### ISSUE TITLE
libqt6pas issue, pls update to 6.2.2

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#12]
I am writing here because in libqt6pas repo I don't get replies. according to
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40011#note_1179738040
we need version 6.2.2, as current version 6.2.0 crashes with my linux app.
@davidbannon

**Comment by davidbannon** [comment]
There are not any open tickets in libqt6pas as near as I can tell.
There was one relating to a week old issue that had been fixed just before it was posted but even thats closed now ?? There were several "re-packages" since that message was posted.

Anyway, I have now released 6.2.2 on the libqt6pas site, untested by me but because it seems you need them in a real hurry, done.

I cannot sit around watching for Z to make an update to the interface, I have to rely on people needing it there and then sending me a message.

Davo

**Comment by Alexey-T** [comment]
Thanks! my app works again.
