### ISSUE TITLE
Publish releases for ARM 32-bit and AArch64, please

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#5]
I see that FPC 3.2-fixes cross for aarch64 gives LibQt5pas files! in the folder "cross/lib/aarch64-linux" I see those N files.

libQt5Pas.so.1
libQt5Pas.so.1.2
libQt5Core.so.5
libQt5Gui.so.5
libQt5Network.so.5
libQt5PrintSupport.so.5
libQt5Widgets.so.5
libQt5X11Extras.so.5
libQt5Pas.so.1.2.9
libQt5Pas.so

 But.... not such files for ARM 32bit in the cross for ARM.

**Comment by davidbannon** [comment]
Alexey, I don't think its necessary is it ?  While some newer distros do offer libqt5pas1 in 2.9 version, the new things that changed between 1.2.8 and 1.2.9 have been removed from Lazarus because of a couple of technical issues. Issues that, as far as I know, have not been fixed and by the sound of it, may not be.

So, you should safely use either 1.2.8 or 1.2.9 with no problems.

Do you have reason to think otherwise ?

The files you list, except for libQt5Pas* are the standard Qt5 available in every distribution that supports Qt5.

Davo
