### ISSUE TITLE
dependancies - too much of them

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#55]
I installed the .deb  packages (one of them) on Ubuntu 20.04 x64. now I get this msg from Ubuntu

![Screenshot from 2023-09-19 19-16-31](https://github.com/davidbannon/libqt5pas/assets/4154978/7d0d02f3-f951-498a-8a4e-2593578df218)

looking into .deb 'control' file I see these dep's. can you remove them?

maybe these 2 dep's are redundant. I see my app CudaText Qt5 version is running ok w/o them.

**Comment by Alexey-T** [comment]
before I installed version  2.15 (or 1.2.15 ? the bad versioning is the issue too!) I had 2.6. and I had no warnings from Ubuntu. after installing 2.15 over 2.6, I got this new warning.

**Comment by davidbannon** [comment]
If you already also have an older version of the DEV package, you must either remove it or also install the new dev package at the same time. Normal apt stuff.

(In the last week, I must have done that ten times testing Z fixes, always worked for me. But if you had  really old libqt5pas1 packages, its possible you may need to remove and reinstall because of some inconsistencies with the names that date back to when this repo started.)

David
