### ISSUE TITLE
version 1.x or 2.x

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#56]
If DEB package system thinks the version is 2.15
```
user@PC:~$ apt list libqt5pas*
Listing... Done
libqt5pas-dev/focal 2.6~beta-6build1 amd64
libqt5pas1/now 2.15 amd64 [installed,local]
user@PC:~$ 
```

then let's name it 2.15 on all GH pages and readmes. currently it is 1.2.15 there.

**Comment by davidbannon** [comment]
Its been numbered like that from the start, way before I had even heard of it. If we change the numbering system, then, when, eg, debian finally release their version of it, its won't happen as it should.

There are serious implications of playing with version numbers. I don't like how it is but I know better than play with it just because I don't like it. 

David
