### ISSUE TITLE
libQt5Pas is not compilable on OpenBSD

### ISSUE THREAD

**Issue by TCH68k** [davidbannon/libqt5pas#59]
I tried to compile libQt5Pas 1.2.15 on OpenBSD 7.5, but failed. After installing Qt5 (`pkg_add Qt5`), i did `cd` into the `cbindings` directory and then did a `qmake-qt5`:
```
Project MESSAGE: Note: This binding version was generated for Qt 5.6.1. Current Qt is 5.15.12
Project MESSAGE: Qt documents binary compatibility in each Version Change Note: http://qt.nokia.com/developer/changes
Project MESSAGE: Adding x11extras for XOrg platform.
Project MESSAGE: Pascal Qt Interface for binding platform: BINUX
Project MESSAGE: Install location: /usr/local/lib/qt5 
```
I don't know what is BINUX and why does it recognize OpenBSD as it, but this might be also a problem. Then i did `gmake`:
```
c++ -c -pipe -Wfatal-errors -w -pthread -fPIC -DBINUX -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB  -I. -I/usr/local/include/X11/qt5 -I/usr/local/include/X11/qt5/QtPrintSupport -I/usr/local/include/X11/qt5/QtWidgets -I/usr/local/include/X11/qt5/QtX11Extras -I/usr/local/include/X11/qt5/QtGui -I/usr/local/include/X11/qt5/QtNetwork -I/usr/local/include/X11/qt5/QtCore -Itmp -I/usr/X11R6/include -I/usr/X11R6/include/libdrm -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/openbsd-clang -o tmp/qobject_hook_c.o src/qobject_hook_c.cpp
In file included from src/qobject_hook_c.cpp:12:
In file included from src/qobject_hook_c.h:15:
In file included from src/qobject_hook.h:17:
In file included from /usr/local/include/X11/qt5/QtCore/qobject.h:46:
In file included from /usr/local/include/X11/qt5/QtCore/qobjectdefs.h:48:
In file included from /usr/local/include/X11/qt5/QtCore/qnamespace.h:43:
In file included from /usr/local/include/X11/qt5/QtCore/qglobal.h:45:
In file included from /usr/include/c++/v1/type_traits:421:
In file included from /usr/include/c++/v1/__functional/invoke.h:15:
In file included from /usr/include/c++/v1/__type_traits/apply_cv.h:15:
In file included from /usr/include/c++/v1/__type_traits/remove_reference.h:13:
In file included from /usr/include/c++/v1/cstddef:41:
./version:1:1: fatal error: expected unqualified-id
1.2.14
```
(Yes, this is libQt5Pas 1.2.15, not 14; `cbindings/version` contains this for some reason.)

Any ideas on this? Is libQt5Pas even supposed to be compilable on OpenBSD?

**Comment by davidbannon** [comment]
Hi tch, I am not really the person to help, all I do here is build and package for a couple of mainstream platforms. You need to speak to [zeljko](https://forum.lazarus.freepascal.org/index.php?action=profile;u=129) over at the Lazarus Forum, https://forum.lazarus.freepascal.org/, he is pretty active there and always very helpful.

The library build process is heavily dependent on gcc and Qt5 libraries and if you can build the main Qt5 libraries, I'd expect that building this one extra library would be the same.  So, please tell zeljiko how you got your Qt5 OpenBSD libraries. Problem seems to rest in the installed QT files rather than Z's code so sounds like an incompatibility ...

My guess is no one else has tried to build or use this library on OpenBSD, but I could be wrong, only time I have every used OpenBSD as headless.

(going to look into that "1.2.14" though, thats unexpected)

Davo

**Comment by davidbannon** [comment]
The file, cbindings/version is contributing the 1.2.14, it ignored by my package scripts that get version info direct from the built binary (and the binary gets ver info from the .pro file). So, should be removed ....
Davo

**Comment by davidbannon** [comment]
Oh ?? Really ?  that cbindings/version should have nothing at all to do with building of the library, it was there to help with the packaging, that is making debs and rpms. Earlier version of my packing script used it, later one gets it from the binary.

I just now rebuilt the binary both with and without that file present and it made no difference.

Anyway, glad its built for you. Thats whats important I guess.

Davo

**Comment by TCH68k** [comment]
On OpenBSD it blocks the compilation. For some reason, something tries to include it and its content is messing up some class definition, or something similar. At least i found class definition problems, if i tried to look up the error message.

Thanks for the help again.

**Comment by davidbannon** [comment]
Removed version file, artifact of old package system but interferes with build in OpenBSD.
