### ISSUE TITLE
Publish ARM and AArch64 binaries too

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#8]
For R-Pi board, I need ARM and AArch64 (arm - not right now, aarch64 - now). Can you please compile them and put to Releases page?

**Comment by davidbannon** [comment]
Yes Alex, should be possible, I have not tried but will give it a go. Because these are not cross compile jobs (gcc not fpc ;-(  ), I'll have to build up a Raspberry Pie 64 bit image on a real Pi. I am in the middle of pre-release for tomboy-ng right now so may be a few days I am afraid.

And finding more bugs in the new tomboy-ng than I expected ...

Davo

**Comment by davidbannon** [comment]
Yes Alex, should be possible, I have not tried but will give it a go. Because these are not cross compile jobs (gcc not fpc ;-(  ), I'll have to build up a Raspberry Pie 64 bit image on a real Pi. I am in the middle of pre-release for tomboy-ng right now so may be a few days I am afraid.

And finding more bugs in the new tomboy-ng than I expected ...

Davo

**Comment by davidbannon** [comment]
OK Alex, I have put a pair of arm64, aka aarch64 libraries on the release page. However, I don't, at present, have any arm64 FPC binaries I can test it with so, its totally untested. Not just the code but, importantly, the package process.
Its debs only as I need to further edit my build scripts to make rpms.

And I am afraid Liz wants to go out shortly to a music festival so cannot do any more today (and probably not until Monday).

If you do test, please watch for any warning while installing and running. And let me know ...

Davo

**Comment by Alexey-T** [comment]
I hope Liz will perform nicely on that meeting. I will wait for your testing of the lib. :)

**Comment by davidbannon** [comment]
OK, I have tested the new arm64 library. All good as near as I can tell. For example, with the repo assigned library, I can build a Qt5 version of Lazarus 2.2.4 but trying to build main fails with this -

> qtobject.inc:43: undefined reference to `QGuiApplication_setFallbackSessionManagementEnabled'

With the new library, both laz 2.2.4 and main build perfectly using Qt5.

Davo

**Comment by Alexey-T** [comment]
Thanks... that error must be reported to the forum I guess.
Did you test ARM64 lib on ARM64 device (R-Pi)?

**Comment by davidbannon** [comment]
No, no report necessary, thats exactly what I would expect. Repo library does not have Z's new 'features', the one I build from main does. All good. If you build your app with main, you must use the new library.

Yes, I did my testing on a Pi 4 with 2G ram, using the Raspberry Pi 64bit OS.

Davo

**Comment by davidbannon** [comment]
OK, arm 32, aka armhf libraries now available too.

Worth noting that the new, bullseye based Raspberry OS does not have GTK2 pre-installed. Its there as a dependency is needed but its a sizable install, 50Meg download, 200Meg disk space.  So, you move to Qt5 on Rasberry Pi probably makes sense.

But will be a challenge to cross compile to I expect.

Davo
