### ISSUE TITLE
for non-Debian OS'es, we need packages in .xz format

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#9]
E.g. for ArchLinux.

**Comment by davidbannon** [comment]
pkg.tar.zst pacman format ?

Easy enough on x86_64 but if you mean armhf or aarch, I am not so sure. I say that because I believe Arch does not officially support Raspberry Pi and while there may be one of more spins, I am not convinced its worth the effort.

On the other hand, I already build x86_64 pacman packages for tomboy_ng so expect it would be easy. The format is simple enough compared to debs or rpms but does require me to tag the code, sort of a release.

Please let me know what you need.

Davo

**Comment by Alexey-T** [comment]
>pkg.tar.zst pacman format ?

no! only .xz which is analog of .zip on unixes. Or .zip will be ok too.

**Comment by Alexey-T** [comment]
I use ArchLinux for ARM64, on Rasperry Pi 3! so to get your libs using, I unpacked the .deb file on my main PC and copied .so files via flash card.

**Comment by davidbannon** [comment]
OK, now I understand. I make a tgz file, a gzipped tar, like that for tomboy-ng, and am surprised how many people download it even though its quite incomplete compared to a deb or a rpm.
So, just the library and perhaps a readme suggesting how it can be manually installed. x86_64, aarch and armhf ?

Davo

**Comment by Alexey-T** [comment]
>So, just the library and perhaps a readme suggesting how it can be manually installed. 

yes

>x86_64, aarch and armhf ?

aarch64! yes

**Comment by davidbannon** [comment]
done

Davo

**Comment by Alexey-T** [comment]
Thanks
